package auth

import (
	"context"
	"fmt"
	"net/http"
	"strings"

	"heal-her-backend-2/cmd/internal/config"

	"github.com/golang-jwt/jwt/v5"
)

// contextKey prevents collision in the request context
type contextKey string

const UserContextKey = contextKey("user_claims")

// UserClaims strictly maps to the JWT payload generated by your Python backend.
// This is the absolute source of truth for the user's identity in the Go microservice.
type UserClaims struct {
	// The Python backend packs the UUID into the standard "sub" (subject) claim.
	ID string `json:"sub"` 
	
	// The Python backend calculates the age segment and locks it here.
	Dashboard string `json:"dashboard"` 
	
	jwt.RegisteredClaims
}

// Middleware intercepts the request, verifies the JWT, and extracts user identity
func Middleware(cfg *config.Config) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Extract token from the Authorization header provided by the Next.js proxy
			authHeader := r.Header.Get("Authorization")
			if authHeader == "" || !strings.HasPrefix(authHeader, "Bearer ") {
				http.Error(w, "Unauthorized: Missing token", http.StatusUnauthorized)
				return
			}

			tokenString := strings.TrimPrefix(authHeader, "Bearer ")

			// Parse and validate the JWT using the shared secret
			claims := &UserClaims{}
			token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
				// Ensure the signing method matches your Python implementation (usually HS256)
				if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
					return nil, fmt.Errorf("unexpected signing method")
				}
				return []byte(cfg.JWTSecret), nil
			})

			if err != nil || !token.Valid {
				http.Error(w, "Unauthorized: Invalid or expired token", http.StatusUnauthorized)
				return
			}

			// Inject the decoded claims into the request context for downstream handlers
			ctx := context.WithValue(r.Context(), UserContextKey, claims)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}